#pragma once
#include "NativeGameplayTags.h"

namespace AuraGameplayTags
{
	/** Input Tags **/
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_None);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LMB);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_RMB);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Passive_1);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Passive_2);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_1);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_2);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_3);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_4);
	
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Block_CursorTrace);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Block_InputPressed);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Block_InputHeld);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Block_InputReleased);

	/** Game Data Tags**/
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Strength);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Intelligence);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Vigor);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Resilience);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_Armor);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_ArmorPenetration);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_BlockChance);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_CriticalHitChance);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_CriticalHitDamage);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_CriticalHitResistance);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_HealthRegeneration);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_ManaRegeneration);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_MaxHealth);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_MaxMana);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_Health);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_Mana);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance_Fire);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance_Lightning);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance_Arcane);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance_Physical);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Meta_IncomingXP);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Fire);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Lightning);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Arcane);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical);

	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Fire);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Stun);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Arcane);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Physical);
	
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Chance);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Damage);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Duration);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Frequency);
	
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_FireBolt);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_Electrocute);

	/** Enemy Tags**/
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_Attack_1);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_Attack_2);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_Attack_3);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_Attack_4);
	
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatSocket_Weapon);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatSocket_LeftHand);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatSocket_RightHand);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatSocket_Tail);

	/** Shared Tags**/
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HealthPotion);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_ManaPotion);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HealthCrystal);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_ManaCrystal);

	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_None);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HitReact);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Melee);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Ranged);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Summon);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill_Fire_FireBolt);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill_Lightning_Electrocute);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill_Arcane_ArcaneShards);
	
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_None);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Offensive);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Passive);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Status_Locked);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Status_Eligible);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Status_Unlocked);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Status_Equipped);
	
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Passive_HaloOfProtection);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Passive_LifeSiphon);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Passive_ManaSiphon);
	
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_Fire_FireBolt);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_Lightning_Electrocute);
	
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_HitReact);

	/** GameplayCue Tags **/
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Enemy_MeleeAttack_Impact);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Aura_Lightning_ShockBurst);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Aura_Lightning_ShockLoop);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Aura_Arcane_Shards);
	
}
